-- MySQL Script generated by MySQL Workbench
-- Wed Jul 11 23:06:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebida` (
  `idbebida` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idbebida`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(145) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `hora_pedido` DATETIME NOT NULL,
  `total` FLOAT NOT NULL,
  `forma_de_pgto` TINYINT(4) NOT NULL,
  `troco` FLOAT NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `origem` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_has_pedido` (
  `cliente_idcliente` INT(11) NOT NULL,
  `pedido_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`cliente_idcliente`, `pedido_ID`),
  INDEX `fk_cliente_has_pedido_pedido1_idx` (`pedido_ID` ASC),
  INDEX `fk_cliente_has_pedido_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_cliente_has_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pedido_pedido1`
    FOREIGN KEY (`pedido_ID`)
    REFERENCES `mydb`.`pedido` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingrediente` (
  `idingrediente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idingrediente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_has_bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_has_bebida` (
  `pedido_ID` INT(10) UNSIGNED NOT NULL,
  `bebida_idbebida` INT(11) NOT NULL,
  PRIMARY KEY (`pedido_ID`, `bebida_idbebida`),
  INDEX `fk_pedido_has_bebida_bebida1_idx` (`bebida_idbebida` ASC),
  INDEX `fk_pedido_has_bebida_pedido1_idx` (`pedido_ID` ASC),
  CONSTRAINT `fk_pedido_has_bebida_bebida1`
    FOREIGN KEY (`bebida_idbebida`)
    REFERENCES `mydb`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_bebida_pedido1`
    FOREIGN KEY (`pedido_ID`)
    REFERENCES `mydb`.`pedido` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(45) NOT NULL,
  `n_de_sabores` INT(11) NOT NULL,
  `borda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_has_pizza` (
  `pedido_ID` INT(10) UNSIGNED NOT NULL,
  `pizza_id` INT(11) NOT NULL,
  PRIMARY KEY (`pedido_ID`, `pizza_id`),
  INDEX `fk_pedido_has_pizza_pizza1_idx` (`pizza_id` ASC),
  INDEX `fk_pedido_has_pizza_pedido1_idx` (`pedido_ID` ASC),
  CONSTRAINT `fk_pedido_has_pizza_pedido1`
    FOREIGN KEY (`pedido_ID`)
    REFERENCES `mydb`.`pedido` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sabor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sabor` (
  `idsabor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsabor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_sabor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_sabor` (
  `pizza_id` INT(11) NOT NULL,
  `sabor_idsabor` INT(11) NOT NULL,
  PRIMARY KEY (`pizza_id`, `sabor_idsabor`),
  INDEX `fk_pizza_has_sabor_sabor1_idx` (`sabor_idsabor` ASC),
  INDEX `fk_pizza_has_sabor_pizza1_idx` (`pizza_id` ASC),
  CONSTRAINT `fk_pizza_has_sabor_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_sabor_sabor1`
    FOREIGN KEY (`sabor_idsabor`)
    REFERENCES `mydb`.`sabor` (`idsabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sabor_has_ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sabor_has_ingrediente` (
  `sabor_idsabor` INT(11) NOT NULL,
  `ingrediente_idingrediente` INT(11) NOT NULL,
  PRIMARY KEY (`sabor_idsabor`, `ingrediente_idingrediente`),
  INDEX `fk_sabor_has_ingrediente_ingrediente1_idx` (`ingrediente_idingrediente` ASC),
  INDEX `fk_sabor_has_ingrediente_sabor_idx` (`sabor_idsabor` ASC),
  CONSTRAINT `fk_sabor_has_ingrediente_ingrediente1`
    FOREIGN KEY (`ingrediente_idingrediente`)
    REFERENCES `mydb`.`ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sabor_has_ingrediente_sabor`
    FOREIGN KEY (`sabor_idsabor`)
    REFERENCES `mydb`.`sabor` (`idsabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas_available`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizzas_available` (
  `idpizzas_available` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `custo_grande` DOUBLE NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`idpizzas_available`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas_available_has_sabor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizzas_available_has_sabor` (
  `pizzas_available_idpizzas_available` INT NOT NULL,
  `sabor_idsabor` INT(11) NOT NULL,
  PRIMARY KEY (`pizzas_available_idpizzas_available`, `sabor_idsabor`),
  INDEX `fk_pizzas_available_has_sabor_sabor1_idx` (`sabor_idsabor` ASC),
  INDEX `fk_pizzas_available_has_sabor_pizzas_available1_idx` (`pizzas_available_idpizzas_available` ASC),
  CONSTRAINT `fk_pizzas_available_has_sabor_pizzas_available1`
    FOREIGN KEY (`pizzas_available_idpizzas_available`)
    REFERENCES `mydb`.`pizzas_available` (`idpizzas_available`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzas_available_has_sabor_sabor1`
    FOREIGN KEY (`sabor_idsabor`)
    REFERENCES `mydb`.`sabor` (`idsabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
